# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7vx485tffg1761-2

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Projects/04-23-test/project_3/project_3.srcs/sources_1/bd/design_1/ipshared/4903
    c:/Projects/04-23-test/project_3/project_3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl
    c:/Projects/04-23-test/project_3/project_3.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0
    c:/Projects/04-23-test/project_3/project_3.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_1
  } {
      C:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_vhdl -lib xil_defaultlib {
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_clk_wiz_1_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_microblaze_0_axi_intc_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_microblaze_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_microblaze_0_xlconcat_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_rst_clk_wiz_1_100M_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_mdm_1_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_dlmb_v10_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_ilmb_v10_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_dlmb_bram_if_cntlr_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_ilmb_bram_if_cntlr_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_lmb_bram_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_axi_uartlite_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_axi_gpio_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_xlslice_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_xlslice_1_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_xlslice_2_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_axi_timer_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_blk_mem_gen_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_xlconstant_3_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_util_ds_buf_1_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_CDR_state_machine_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_serial_pipeline_delay_0_1_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_FIFO_enabler_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_util_vector_logic_0_1_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_fifo_filled_lock_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_address_counter_16_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_blk_mem_gen_0_1_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_util_vector_logic_1_1_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_util_vector_logic_2_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_serial_pipeline_delay_1_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_serial_pipeline_delay_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_serial_pipeline_delay_3_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_Buffer_help_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_oversample_8x_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_os48_1011x20bTo10b_top2_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_xlconstant_1_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_xlconstant_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_b10_to_2b_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_xbar_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_address_counter_1_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_clock_change_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_clock_change_1_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_Head_state_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_util_vector_logic_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_c_accum_0_2_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_fifo_generator_0_1_stub.vhdl
      C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/realtime/design_1_error_valid_0_0_stub.vhdl
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/imports/sources_1/new/CDR_state_machine.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/new/serial_pipeline_delay.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/imports/sources_1/new/FIFO_enabler.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/imports/sources_1/new/fifo_filled_lock.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/imports/sources_1/new/address_counter_16.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/imports/sources_1/new/Buffer.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/imports/sources_1/imports/VHDL/oversample_8x.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/imports/sources_1/imports/VHDL/PKG_XILINX.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/imports/sources_1/imports/VHDL/PKG_OVERSAMP.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/imports/sources_1/imports/VHDL/ff_fifo2e.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/imports/sources_1/imports/VHDL/ff_fifo2e_10b.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/imports/sources_1/imports/VHDL/os48_1011x20bTo10b.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/imports/sources_1/imports/VHDL/osDeci20b_48_1011x_BRAM.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/imports/sources_1/imports/VHDL/sipoCtl10b_BRAM_v2_virtex5.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/imports/sources_1/imports/VHDL/os48_1011x20bTo10b_top2.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/imports/sources_1/new/10b_to_2b.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/imports/sources_1/imports/new/address_counter.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/new/clock_change.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/imports/new/Head_state.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/new/protect_fifo.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/bd/design_1/synth/design_1.vhd
      C:/Projects/04-23-test/project_3/project_3.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top design_1_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Projects/04-23-test/project_3/.Xil/Vivado-7560-PHSX-82QWMN2/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
